#!/bin/bash

# Script to create realistic task directories for php-simpletasks-Roadmap

PROJECT_ROADMAP_DIR="php-simpletasks-Roadmap"
# Ensure the main project roadmap directory exists
# Check if the directory already exists to avoid error messages if run multiple times
if [ ! -d "$PROJECT_ROADMAP_DIR" ]; then
    mkdir -p "$PROJECT_ROADMAP_DIR"
    echo "Created project directory: $PROJECT_ROADMAP_DIR"
else
    echo "Project directory already exists: $PROJECT_ROADMAP_DIR"
fi


# UI Enhancements
mkdir -p "$PROJECT_ROADMAP_DIR/UI--RedesignProjectHeadersForEnhancedClarity"
mkdir -p "$PROJECT_ROADMAP_DIR/UI--ImplementSmoothScrollForLongProjectLists"
mkdir -p "$PROJECT_ROADMAP_DIR/UI--AddVisualCuesForTaskNestingLevels"
mkdir -p "$PROJECT_ROADMAP_DIR/UI--DevelopCustomIconSetForTaskStatusIndicators"
mkdir -p "$PROJECT_ROADMAP_DIR/UI--ImproveThemeToggleTransitionAnimation"
mkdir -p "$PROJECT_ROADMAP_DIR/UI--StandardizeModalDialogAppearanceAndBehavior"
mkdir -p "$PROJECT_ROADMAP_DIR/UI--EnhanceEmptyStateUIWithHelpfulSuggestions"
mkdir -p "$PROJECT_ROADMAP_DIR/UI--CreateAlternativeCompactViewForDenseTaskLists"
mkdir -p "$PROJECT_ROADMAP_DIR/UI--RefineFocusStylesForAllInteractiveUIElements"
mkdir -p "$PROJECT_ROADMAP_DIR/UI--ImplementSkeletonLoaderEffectForInitialPageLoad"
mkdir -p "$PROJECT_ROADMAP_DIR/UI--DesignUserSelectableAccentColorsForThemes"
mkdir -p "$PROJECT_ROADMAP_DIR/UI--UpdateApplicationFaviconAndManifestIcons"
mkdir -p "$PROJECT_ROADMAP_DIR/UI--ImproveVisualHierarchyAndSpacingOfElements"
mkdir -p "$PROJECT_ROADMAP_DIR/UI--AddOptionToToggleInlineTaskDetailsExpansion"
mkdir -p "$PROJECT_ROADMAP_DIR/UI--DevelopAndRefinePrintSpecificStylesheet"
mkdir -p "$PROJECT_ROADMAP_DIR/UI--AnimateProjectCardExpansionAndCollapse"
mkdir -p "$PROJECT_ROADMAP_DIR/UI--EnsureConsistentTypographyAcrossAllViews"
mkdir -p "$PROJECT_ROADMAP_DIR/UI--DesignCentralizedSettingsPanelForUserPreferences"
mkdir -p "$PROJECT_ROADMAP_DIR/UI--AddVisualIndicatorForActiveFiltersAndSort"
mkdir -p "$PROJECT_ROADMAP_DIR/UI--ImplementSubtleHoverEffectsForInteractiveItems"
mkdir -p "$PROJECT_ROADMAP_DIR/UI--RefineBorderAndShadowStylesForModernLook"
mkdir -p "$PROJECT_ROADMAP_DIR/UI--CreateLoadingSpinnerComponentForAsyncOperations"
mkdir -p "$PROJECT_ROADMAP_DIR/UI--ImproveReadabilityOfTaskTextAndMetadata"
mkdir -p "$PROJECT_ROADMAP_DIR/UI--AddQuickThemePreviewInSettings"
mkdir -p "$PROJECT_ROADMAP_DIR/UI--StandardizeIconUsageAcrossTheApplication"

# UX Improvements
mkdir -p "$PROJECT_ROADMAP_DIR/UX--ImplementDragAndDropForTaskReordering"
mkdir -p "$PROJECT_ROADMAP_DIR/UX--AddGlobalKeyboardShortcutForQuickProjectSearch"
mkdir -p "$PROJECT_ROADMAP_DIR/UX--ImproveProjectFilterWithRealTimeSuggestions"
mkdir -p "$PROJECT_ROADMAP_DIR/UX--PersistUserInterfaceCustomizationsLocalStorage"
mkdir -p "$PROJECT_ROADMAP_DIR/UX--ProvideClearerUserFeedbackForCopyActions"
mkdir -p "$PROJECT_ROADMAP_DIR/UX--StreamlineOnboardingProcessForFirstTimeUsers"
mkdir -p "$PROJECT_ROADMAP_DIR/UX--ConductHeuristicEvaluationOfCoreUserFlows"
mkdir -p "$PROJECT_ROADMAP_DIR/UX--AddContextualTooltipsForAdvancedFeatures"
mkdir -p "$PROJECT_ROADMAP_DIR/UX--AllowUsersToCustomizeDisplayedColumnsInTaskList"
mkdir -p "$PROJECT_ROADMAP_DIR/UX--ImproveNavigationBetweenDifferentAppSections"
mkdir -p "$PROJECT_ROADMAP_DIR/UX--AddConfirmationDialogsForProjectDeletion"
mkdir -p "$PROJECT_ROADMAP_DIR/UX--GatherUserFeedbackOnNewSearchFunctionality"
mkdir -p "$PROJECT_ROADMAP_DIR/UX--SimplifyProcessOfExportingProjectData"
mkdir -p "$PROJECT_ROADMAP_DIR/UX--TestAndOptimizeMobileUsabilityOnVariousScreenSizes"
mkdir -p "$PROJECT_ROADMAP_DIR/UX--AllowPinningFavoriteProjectsToDashboard"
mkdir -p "$PROJECT_ROADMAP_DIR/UX--ImplementBulkTaskActionsLikeMarkAsDone"
mkdir -p "$PROJECT_ROADMAP_DIR/UX--CreateInteractiveTutorialForNewFeatureRollouts"
mkdir -p "$PROJECT_ROADMAP_DIR/UX--PersonalizeViewBasedOnFrequentlyAccessedProjects"
mkdir -p "$PROJECT_ROADMAP_DIR/UX--ReduceNumberOfClicksForCommonTaskOperations"
mkdir -p "$PROJECT_ROADMAP_DIR/UX--AddSmartDefaultsForNewProjectCreation"
mkdir -p "$PROJECT_ROADMAP_DIR/UX--ImproveErrorMessageReadabilityAndHelpfulness"
mkdir -p "$PROJECT_ROADMAP_DIR/UX--AllowUserToSetDefaultSortOrderForTasks"
mkdir -p "$PROJECT_ROADMAP_DIR/UX--ResearchAndImplementUserActivityLoggingForAnalytics"
mkdir -p "$PROJECT_ROADMAP_DIR/UX--AddOptionToCollapseAllOrExpandAllProjects"

# Feature Development
mkdir -p "$PROJECT_ROADMAP_DIR/Feature--SupportTaskDependenciesViaFolderNameConvention"
mkdir -p "$PROJECT_ROADMAP_DIR/Feature--ImplementRecurringTasksBasedOnCronLikeSyntaxInName"
mkdir -p "$PROJECT_ROADMAP_DIR/Feature--AddProjectTemplatesFromUserDefinedStructures"
mkdir -p "$PROJECT_ROADMAP_DIR/Feature--AllowAssigningColorCodesToProjects"
mkdir -p "$PROJECT_ROADMAP_DIR/Feature--ImplementGlobalSearchWithHighlightingResults"
mkdir -p "$PROJECT_ROADMAP_DIR/Feature--AddSupportForMarkdownInTaskDescriptionsViaMetaFile"
mkdir -p "$PROJECT_ROADMAP_DIR/Feature--SupportFileAttachmentsInTaskSubfolderWithPreview"
mkdir -p "$PROJECT_ROADMAP_DIR/Feature--ImplementBasicTimeTrackingStartStopPerTask"
mkdir -p "$PROJECT_ROADMAP_DIR/Feature--AddNotificationsForTasksDueTodayViaBrowserAPI"
mkdir -p "$PROJECT_ROADMAP_DIR/Feature--AllowCustomizableTaskStatusBeyondCheckbox"
mkdir -p "$PROJECT_ROADMAP_DIR/Feature--ImplementProjectProgressVisualizationPercentage"
mkdir -p "$PROJECT_ROADMAP_DIR/Feature--AddBatchTaskEditingForStatusAndPriority"
mkdir -p "$PROJECT_ROADMAP_DIR/Feature--SupportTaskCommentsStoredInAssociatedTextFile"
mkdir -p "$PROJECT_ROADMAP_DIR/Feature--CreateReadOnlySharableLinksForIndividualProjects"
mkdir -p "$PROJECT_ROADMAP_DIR/Feature--AddAbilityToArchiveAndUnarchiveProjects"
mkdir -p "$PROJECT_ROADMAP_DIR/Feature--SupportTaskRemindersXDaysBeforeDueDate"
mkdir -p "$PROJECT_ROADMAP_DIR/Feature--ImplementTaggingSystemForTasksUsingFileNamePatterns"
mkdir -p "$PROJECT_ROADMAP_DIR/Feature--AddProjectGoalsOrDescriptionsField"
mkdir -p "$PROJECT_ROADMAP_DIR/Feature--AllowFilteringTasksByMultipleCriteriaTagsStatus"
mkdir -p "$PROJECT_ROADMAP_DIR/Feature--DisplayLastModifiedTimestampForProjectsAndTasks"
mkdir -p "$PROJECT_ROADMAP_DIR/Feature--AddOptionToHideCompletedTasks"
mkdir -p "$PROJECT_ROADMAP_DIR/Feature--SupportTaskPrioritizationHighMediumLowFromName"
mkdir -p "$PROJECT_ROADMAP_DIR/Feature--GenerateChangeLogFromTaskCompletionHistory"
mkdir -p "$PROJECT_ROADMAP_DIR/Feature--AddSimpleAnalyticsDashboardWithinApp"
mkdir -p "$PROJECT_ROADMAP_DIR/Feature--ImplementExportToICALForTasksWithDates"

# Core PHP Backend
mkdir -p "$PROJECT_ROADMAP_DIR/Core--RefactorDirectoryScanningToUseSymfonyFinder"
mkdir -p "$PROJECT_ROADMAP_DIR/Core--ImplementPSR3CompatibleLoggingMechanism"
mkdir -p "$PROJECT_ROADMAP_DIR/Core--AddSupportForIgnoringFilesViaWildcardPatternsInConfig"
mkdir -p "$PROJECT_ROADMAP_DIR/Core--OptimizePHPMemoryFootprintForLargeDirectoryTrees"
mkdir -p "$PROJECT_ROADMAP_DIR/Core--DevelopLightweightPluginAPIToExtendFunctionality"
mkdir -p "$PROJECT_ROADMAP_DIR/Core--EnsureRobustHandlingOfUTF8FileNamesAcrossPlatforms"
mkdir -p "$PROJECT_ROADMAP_DIR/Core--ImplementETagAndLastModifiedHeadersForAPICaching"
mkdir -p "$PROJECT_ROADMAP_DIR/Core--EnforceStrictPHPDocStandardForAllCode"
mkdir -p "$PROJECT_ROADMAP_DIR/Core--IntroduceBasicFrontControllerIfAppGrowsToMultipleActions"
mkdir -p "$PROJECT_ROADMAP_DIR/Core--SanitizeAllDynamicDataInHTMLAttributesAndJS"
mkdir -p "$PROJECT_ROADMAP_DIR/Core--CreateAbstractionForReadingTaskMetadataFromFiles"
mkdir -p "$PROJECT_ROADMAP_DIR/Core--AddSupportForPHP81EnumsForTaskStatus"
mkdir -p "$PROJECT_ROADMAP_DIR/Core--RefactorConfigurationLoadingToSupportMultipleFormats"
mkdir -p "$PROJECT_ROADMAP_DIR/Core--ImprovePerformanceOfRecursiveTaskCounting"
mkdir -p "$PROJECT_ROADMAP_DIR/Core--HandleFilesystemPermissionsIssuesGracefully"
mkdir -p "$PROJECT_ROADMAP_DIR/Core--ImplementFileLockingForTaskModificationOperations"
mkdir -p "$PROJECT_ROADMAP_DIR/Core--ValidateProjectAndTaskNameFormatsAgainstConfigurableRules"
mkdir -p "$PROJECT_ROADMAP_DIR/Core--DevelopSystemHealthCheckEndpointWithVitalStats"
mkdir -p "$PROJECT_ROADMAP_DIR/Core--CacheParsedDirectoryStructureInMemoryWithTTL"
mkdir -p "$PROJECT_ROADMAP_DIR/Core--AddPHPMailerIntegrationForEmailNotifications"
mkdir -p "$PROJECT_ROADMAP_DIR/Core--ImplementSessionManagementIfUserAccountsAreAdded"
mkdir -p "$PROJECT_ROADMAP_DIR/Core--RefactorExclusionLogicToBeMoreExtensible"
mkdir -p "$PROJECT_ROADMAP_DIR/Core--AddComposerScriptForCodeQualityChecks"
mkdir -p "$PROJECT_ROADMAP_DIR/Core--UpdatePHPVersionTargetAndLeverageNewFeatures"
mkdir -p "$PROJECT_ROADMAP_DIR/Core--ImplementAPIVersioningStrategy"

# Frontend JavaScript
mkdir -p "$PROJECT_ROADMAP_DIR/Frontend--RefactorThemeToggleToUseModernJSClasses"
mkdir -p "$PROJECT_ROADMAP_DIR/Frontend--ImplementClientSideFuzzySearchUsingFuseJS"
mkdir -p "$PROJECT_ROADMAP_DIR/Frontend--AddBasicOfflineSupportUsingServiceWorkerCache"
mkdir -p "$PROJECT_ROADMAP_DIR/Frontend--OptimizeDOMUpdatesUsingVirtualDOMConceptManually"
mkdir -p "$PROJECT_ROADMAP_DIR/Frontend--ImplementVirtualScrollingForProjectList"
mkdir -p "$PROJECT_ROADMAP_DIR/Frontend--AddComprehensiveKeyboardNavigationForAccessibility"
mkdir -p "$PROJECT_ROADMAP_DIR/Frontend--SetupESLintWithStricterRulesForCodeQuality"
mkdir -p "$PROJECT_ROADMAP_DIR/Frontend--ModularizeJavaScriptCodeIntoES6Modules"
mkdir -p "$PROJECT_ROADMAP_DIR/Frontend--AddVisualFeedbackForPendingBackendRequests"
mkdir -p "$PROJECT_ROADMAP_DIR/Frontend--ImplementDebouncingForFrequentUIEventsLikeSearchInput"
mkdir -p "$PROJECT_ROADMAP_DIR/Frontend--ExpandLocalStorageUsageForUserPreferences"
mkdir -p "$PROJECT_ROADMAP_DIR/Frontend--CreateAndConfigurePWAmanifestJSONFile"
mkdir -p "$PROJECT_ROADMAP_DIR/Frontend--UseIntersectionObserverToLazyLoadProjectDetails"
mkdir -p "$PROJECT_ROADMAP_DIR/Frontend--ImplementClientSideValidationForAnyNewForms"
mkdir -p "$PROJECT_ROADMAP_DIR/Frontend--CreateAGlobalStateManagerForComplexUIInteractions"
mkdir -p "$PROJECT_ROADMAP_DIR/Frontend--OptimizeJavaScriptBundleSizeUsingRollupOrWebpack"
mkdir -p "$PROJECT_ROADMAP_DIR/Frontend--AddGlobalErrorHandlingForJavaScriptExceptions"
mkdir -p "$PROJECT_ROADMAP_DIR/Frontend--EnsureGracefulDegradationWhenJSIsDisabledForCoreView"
mkdir -p "$PROJECT_ROADMAP_DIR/Frontend--ImplementRealTimeUpdatesForTaskChangesUsingPolling"
mkdir -p "$PROJECT_ROADMAP_DIR/Frontend--AddCopyToClipboardForTaskDetails"
mkdir -p "$PROJECT_ROADMAP_DIR/Frontend--DevelopClientSideSortingForTaskColumns"
mkdir -p "$PROJECT_ROADMAP_DIR/Frontend--IntegrateChartJSForVisualizingTaskStats"
mkdir -p "$PROJECT_ROADMAP_DIR/Frontend--RefactorDateHandlingWithLuxonOrDayJS"
mkdir -p "$PROJECT_ROADMAP_DIR/Frontend--AddToastNotificationComponentForUserFeedback"
mkdir -p "$PROJECT_ROADMAP_DIR/Frontend--ImplementFocusTrapForModalDialogs"

# Configuration
mkdir -p "$PROJECT_ROADMAP_DIR/Config--AllowCustomizingExcludedDirPatternsViaJSONFile"
mkdir -p "$PROJECT_ROADMAP_DIR/Config--MakeUIDateFormatSelectableByTheUser"
mkdir -p "$PROJECT_ROADMAP_DIR/Config--AddOptionToSetInitialThemeOverrideSystemPreference"
mkdir -p "$PROJECT_ROADMAP_DIR/Config--EnableOrDisableAutomaticNightModeViaSettingsUI"
mkdir -p "$PROJECT_ROADMAP_DIR/Config--DefineCustomizableTaskPrefixesForStatusInConfig"
mkdir -p "$PROJECT_ROADMAP_DIR/Config--AllowSettingMaxDirectoryScanDepthViaEnvVariable"
mkdir -p "$PROJECT_ROADMAP_DIR/Config--ExternalizeAllCSSColorVariablesForEasyTheming"
mkdir -p "$PROJECT_ROADMAP_DIR/Config--DocumentAllPHPConstantsAndTheirPurpose"
mkdir -p "$PROJECT_ROADMAP_DIR/Config--AddVersionNumberDisplayInFooterFromPHPConstant"
mkdir -p "$PROJECT_ROADMAP_DIR/Config--AllowUserToDefineCustomProjectCategories"
mkdir -p "$PROJECT_ROADMAP_DIR/Config--SupportMultipleDataDirectoriesViaConfig"
mkdir -p "$PROJECT_ROADMAP_DIR/Config--AddSettingForTasksPerPageIfPaginationIsAdded"
mkdir -p "$PROJECT_ROADMAP_DIR/Config--EnableOrDisableSpecificFeaturesViaFlags"
mkdir -p "$PROJECT_ROADMAP_DIR/Config--StoreAppConfigurationInDotEnvFile"
mkdir -p "$PROJECT_ROADMAP_DIR/Config--ProvideExampleConfigurationFileWithAllOptions"

# Testing
mkdir -p "$PROJECT_ROADMAP_DIR/Test--WriteUnitTestsForDirectoryFilteringLogic"
mkdir -p "$PROJECT_ROADMAP_DIR/Test--SetupPHPUnitWithCodeCoverageReporting"
mkdir -p "$PROJECT_ROADMAP_DIR/Test--CreateIntegrationTestsForProjectAndTaskRendering"
mkdir -p "$PROJECT_ROADMAP_DIR/Test--ImplementJavaScriptUnitTestsForThemeSwitcherUsingJest"
mkdir -p "$PROJECT_ROADMAP_DIR/Test--AddTestsForCorrectHandlingOfSpecialCharactersInPaths"
mkdir -p "$PROJECT_ROADMAP_DIR/Test--AutomateRunningTestsOnCommitUsingGitHubActions"
mkdir -p "$PROJECT_ROADMAP_DIR/Test--WriteTestsForTaskMetadataParsingIfImplemented"
mkdir -p "$PROJECT_ROADMAP_DIR/Test--VerifyHTMLOutputIsValidAndCompliesWithAccessibilityStandards"
mkdir -p "$PROJECT_ROADMAP_DIR/Test--TestPerformanceOfDirectoryScanningWith10000Items"
mkdir -p "$PROJECT_ROADMAP_DIR/Test--ImplementEndToEndTestsForCoreUserFlowsUsingPlaywright"
mkdir -p "$PROJECT_ROADMAP_DIR/Test--AddVisualRegressionTestingForUIComponents"
mkdir -p "$PROJECT_ROADMAP_DIR/Test--TestCrossBrowserCompatibilityForCoreFeatures"
mkdir -p "$PROJECT_ROADMAP_DIR/Test--WriteSecurityTestsForInputSanitization"
mkdir -p "$PROJECT_ROADMAP_DIR/Test--MockFileSystemForReliableDirectoryTests"
mkdir -p "$PROJECT_ROADMAP_DIR/Test--TestAPIEndpointsIfDevelopedWithVariousInputs"

# Documentation
mkdir -p "$PROJECT_ROADMAP_DIR/Docs--CreateComprehensiveUserGuideWithScreenshots"
mkdir -p "$PROJECT_ROADMAP_DIR/Docs--DocumentInternalCodeArchitectureAndDataFlow"
mkdir -p "$PROJECT_ROADMAP_DIR/Docs--AddExamplesOfAdvancedFolderNameConventionsForFeatures"
mkdir -p "$PROJECT_ROADMAP_DIR/Docs--WriteDetailedContributionGuidelinesForDevelopers"
mkdir -p "$PROJECT_ROADMAP_DIR/Docs--GeneratePHPDocHTMLOutputAndHostIt"
mkdir -p "$PROJECT_ROADMAP_DIR/Docs--CreateFAQSectionBasedOnCommonUserQueries"
mkdir -p "$PROJECT_ROADMAP_DIR/Docs--ExplainThemeCustomizationAndCreationProcess"
mkdir -p "$PROJECT_ROADMAP_DIR/Docs--DocumentAllAvailableKeyboardShortcuts"
mkdir -p "$PROJECT_ROADMAP_DIR/Docs--MaintainAnUpToDateCHANGELOGFile"
mkdir -p "$PROJECT_ROADMAP_DIR/Docs--AddDeveloperSetupGuideForNewContributors"
mkdir -p "$PROJECT_ROADMAP_DIR/Docs--DocumentConfigurationOptionsAndTheirEffects"
mkdir -p "$PROJECT_ROADMAP_DIR/Docs--CreateTutorialsForUsingNewOrComplexFeatures"
mkdir -p "$PROJECT_ROADMAP_DIR/Docs--ExplainThePluginAPIIfDeveloped"
mkdir -p "$PROJECT_ROADMAP_DIR/Docs--AddTroubleshootingGuideForCommonIssues"
mkdir -p "$PROJECT_ROADMAP_DIR/Docs--DocumentTheReleaseProcess"

# Performance Optimization
mkdir -p "$PROJECT_ROADMAP_DIR/Perf--BenchmarkDirectoryScanningAndOptimizeHotspots"
mkdir -p "$PROJECT_ROADMAP_DIR/Perf--ImplementServerSideRenderingForInitialViewIfSPA"
mkdir -p "$PROJECT_ROADMAP_DIR/Perf--MinifyAndCompressAllStaticAssetsCSSJSImages"
mkdir -p "$PROJECT_ROADMAP_DIR/Perf--OptimizeImageAssetsUsingToolsLikeImageOptim"
mkdir -p "$PROJECT_ROADMAP_DIR/Perf--ReduceDOMManipulationsInCriticalJSPaths"
mkdir -p "$PROJECT_ROADMAP_DIR/Perf--ImplementHTTP2ServerPushForCriticalAssets"
mkdir -p "$PROJECT_ROADMAP_DIR/Perf--AnalyzeAndOptimizeServerResponseTimesTTFB"
mkdir -p "$PROJECT_ROADMAP_DIR/Perf--LazyLoadNonCriticalCSSAndJavaScriptModules"
mkdir -p "$PROJECT_ROADMAP_DIR/Perf--OptimizeFontLoadingStrategyUsingFontDisplay"
mkdir -p "$PROJECT_ROADMAP_DIR/Perf--ProfilePHPExecutionAndMemoryUsageUnderLoad"
mkdir -p "$PROJECT_ROADMAP_DIR/Perf--InvestigateAndImplementOpcodeCachingLikeAPCu"
mkdir -p "$PROJECT_ROADMAP_DIR/Perf--ImplementConnectionPoolingIfDatabaseIsUsed"
mkdir -p "$PROJECT_ROADMAP_DIR/Perf--AnalyzeFrontendPerformanceWithLighthouse"
mkdir -p "$PROJECT_ROADMAP_DIR/Perf--SetPerformanceBudgetsForKeyMetrics"
mkdir -p "$PROJECT_ROADMAP_DIR/Perf--OptimizeClientSideRenderingOfLargeLists"

# Accessibility
mkdir -p "$PROJECT_ROADMAP_DIR/Access--EnsureSufficientColorContrastAcrossAllThemesWCAGAA"
mkdir -p "$PROJECT_ROADMAP_DIR/Access--AddARIALiveRegionsForDynamicContentUpdates"
mkdir -p "$PROJECT_ROADMAP_DIR/Access--VerifyAndCorrectKeyboardFocusOrderAndVisibility"
mkdir -p "$PROJECT_ROADMAP_DIR/Access--ConductThoroughTestingWithScreenReadersJAWSNVDAVoiceOver"
mkdir -p "$PROJECT_ROADMAP_DIR/Access--EnsureAllInteractiveElementsAreKeyboardAccessibleAndFocusable"
mkdir -p "$PROJECT_ROADMAP_DIR/Access--ProvideTextAlternativesForAllNonTextContentIconsImages"
mkdir -p "$PROJECT_ROADMAP_DIR/Access--UseSemanticHTML5ElementsAppropriatelyForStructure"
mkdir -p "$PROJECT_ROADMAP_DIR/Access--CheckAndEnsurePageZoomFunctionalityUpTo400Percent"
mkdir -p "$PROJECT_ROADMAP_DIR/Access--ImplementSkipToContentLinkForKeyboardUsers"
mkdir -p "$PROJECT_ROADMAP_DIR/Access--EnsureFormsHaveProperLabelsAndARIAAttributes"
mkdir -p "$PROJECT_ROADMAP_DIR/Access--ProvideUserPreferenceToReduceMotion"
mkdir -p "$PROJECT_ROADMAP_DIR/Access--DocumentAccessibilityFeaturesAndConformanceLevel"
mkdir -p "$PROJECT_ROADMAP_DIR/Access--RegularlyAuditForAccessibilityCompliance"
mkdir -p "$PROJECT_ROADMAP_DIR/Access--TrainDevelopmentTeamOnAccessibilityBestPractices"
mkdir -p "$PROJECT_ROADMAP_DIR/Access--EnsureDynamicErrorMessagesAreAnnouncedByScreenReaders"

# Security
mkdir -p "$PROJECT_ROADMAP_DIR/Security--ReviewAndReinforceInputSanitizationForAllUserControlledData"
mkdir -p "$PROJECT_ROADMAP_DIR/Security--PreventDirectoryTraversalVulnerabilitiesInAllFilePaths"
mkdir -p "$PROJECT_ROADMAP_DIR/Security--SetAppropriateHTTPSecurityHeadersCSPXFrameOptionsEtc"
mkdir -p "$PROJECT_ROADMAP_DIR/Security--RegularlyScanDependenciesForKnownVulnerabilitiesSnyk"
mkdir -p "$PROJECT_ROADMAP_DIR/Security--ImplementStrictContentSecurityPolicyCSP"
mkdir -p "$PROJECT_ROADMAP_DIR/Security--EnsureNoSensitiveInformationIsExposedInClientSideCode"
mkdir -p "$PROJECT_ROADMAP_DIR/Security--EnforceHTTPSAcrossTheEntireApplication"
mkdir -p "$PROJECT_ROADMAP_DIR/Security--ProtectAgainstCrossSiteScriptingXSSInAllOutputs"
mkdir -p "$PROJECT_ROADMAP_DIR/Security--DisableWebServerDirectoryListingForNonEssentialPaths"
mkdir -p "$PROJECT_ROADMAP_DIR/Security--ReviewAndEnforceCorrectFilePermissionsOnServer"
mkdir -p "$PROJECT_ROADMAP_DIR/Security--ImplementRateLimitingForAnyPotentialAPIEndpoints"
mkdir -p "$PROJECT_ROADMAP_DIR/Security--ProtectAgainstCSRFVulnerabilitiesIfFormsAreAdded"
mkdir -p "$PROJECT_ROADMAP_DIR/Security--ConductRegularSecurityAuditsAndPenetrationTesting"
mkdir -p "$PROJECT_ROADMAP_DIR/Security--DevelopAnIncidentResponsePlan"
mkdir -p "$PROJECT_ROADMAP_DIR/Security--UsePreparedStatementsForAllDatabaseQueriesIfAdded"

# Refactoring
mkdir -p "$PROJECT_ROADMAP_DIR/Refactor--BreakDownMonolithicIndexPHPIntoSmallerModules"
mkdir -p "$PROJECT_ROADMAP_DIR/Refactor--ConsolidateAndOrganizeCSSIntoBEMOrITCSSStructure"
mkdir -p "$PROJECT_ROADMAP_DIR/Refactor--ImproveVariableNameAndFunctionNameClarity"
mkdir -p "$PROJECT_ROADMAP_DIR/Refactor--MoveAllInlineJavaScriptToDedicatedJSFiles"
mkdir -p "$PROJECT_ROADMAP_DIR/Refactor--AdoptAndEnforcePHPStanLevel7OrHigher"
mkdir -p "$PROJECT_ROADMAP_DIR/Refactor--UpdateLegacyPHPCodeToModernBestPractices"
mkdir -p "$PROJECT_ROADMAP_DIR/Refactor--CentralizeStringLiteralsForFutureLocalization"
mkdir -p "$PROJECT_ROADMAP_DIR/Refactor--IdentifyAndRemoveDeadOrUnusedCodePaths"
mkdir -p "$PROJECT_ROADMAP_DIR/Refactor--StandardizeCodeFormattingUsingPHPCSAndPrettier"
mkdir -p "$PROJECT_ROADMAP_DIR/Refactor--SimplifyComplexConditionalLogicInCoreFunctions"
mkdir -p "$PROJECT_ROADMAP_DIR/Refactor--IntroduceDTOSForDataTransferBetweenLayers"
mkdir -p "$PROJECT_ROADMAP_DIR/Refactor--ReplaceGlobalVariablesWithDependencyInjection"
mkdir -p "$PROJECT_ROADMAP_DIR/Refactor--ImproveCodeCommentsAndPHPDocs"
mkdir -p "$PROJECT_ROADMAP_DIR/Refactor--MigrateToAWellKnownTemplateEngineLikeTwig"
mkdir -p "$PROJECT_ROADMAP_DIR/Refactor--DecoupleBusinessLogicFromPresentationLogic"

# Build and Deployment
mkdir -p "$PROJECT_ROADMAP_DIR/Build--SetupAutomatedBuildProcessWithAntOrPhing"
mkdir -p "$PROJECT_ROADMAP_DIR/Build--ImplementCIAndCDPipelineUsingGitHubActionsOrJenkins"
mkdir -p "$PROJECT_ROADMAP_DIR/Build--CreateDockerfilesForDevelopmentAndProductionEnvironments"
mkdir -p "$PROJECT_ROADMAP_DIR/Build--AutomateMinificationAndConcatenationOfAssets"
mkdir -p "$PROJECT_ROADMAP_DIR/Build--AddAutomatedVersionTaggingAndReleaseNotesGeneration"
mkdir -p "$PROJECT_ROADMAP_DIR/Build--ImplementPreCommitHooksForCodeLintingAndFormatting"
mkdir -p "$PROJECT_ROADMAP_DIR/Build--DevelopScriptForEasyDeploymentToStagingAndProduction"
mkdir -p "$PROJECT_ROADMAP_DIR/Build--IntegrateCodeCoverageReportsIntoBuildProcess"
mkdir -p "$PROJECT_ROADMAP_DIR/Build--AutomateDatabaseMigrationsIfDatabaseIsUsed"
mkdir -p "$PROJECT_ROADMAP_DIR/Build--CreatePackagedDistributionOfApplication"

echo "Created 240 task directories under $PROJECT_ROADMAP_DIR"
echo "To make the script executable, run: chmod +x demo.sh"
echo "Then run the script with: ./demo.sh"
