version: '3.8'

services:
  php:
    image: php:8-apache # Uses the latest available PHP 8.x with Apache
    ports:
      - "8080:80" # Map host port 8080 to container port 80
    volumes:
      - .:/var/www/html # Mounts the current repository into /var/www/html
    # Apache within this container runs as www-data by default and serves from /var/www/html.
    # No ports are exposed for Apache as per the request focusing on Samba.

  samba:
    image: docker.io/dperson/samba # Especifica el registro completo de la imagen
    ports:
      - "1137:137/udp" # Host:Container
      - "1138:138/udp" # Host:Container
      - "1139:139/tcp" # Host:Container
      - "1445:445/tcp" # Host:Container
    volumes:
      # Mounts the current repository to /var/www/html inside the Samba container.
      # This is the same host directory mounted by the php service.
      - .:/var/www/html
    # Command to configure Samba:
    # -u "samba_user;samba_password" # Defines a Samba user and password.
    #    IMPORTANT: Change 'devuser' and 'devpass' to secure credentials.
    # -s "<share_name>;</path_in_container>[;browseable;readonly;guest_ok;valid_users;;write_list;comment;extra_smb_options...]"
    #    share_name: Name of the share (e.g., 'repo_share').
    #    path_in_container: Path to share from within the Samba container (e.g., '/var/www/html').
    #    browseable: 'yes' or 'no'.
    #    readonly: 'yes' for read-only, 'no' for read-write.
    #    guest_ok: 'yes' to allow guest access, 'no' to require authentication.
    #    valid_users: Comma-separated list of users allowed to access.
    #    write_list: Comma-separated list of users allowed to write.
    #    comment: Description of the share.
    #    extra_smb_options: Additional smb.conf options for the share, e.g., 'force user=www-data'.
    #       'force user=www-data' and 'force group=www-data' ensure that file operations
    #       are performed as the 'www-data' user and group, effectively making files
    #       owned by www-data:www-data as requested.
    command: >
      -u "devuser;devpass"
      -s "tasks;/var/www/html;yes;no;no;devuser;;devuser;Shared Repository;force user=www-data;force group=www-data"
    restart: unless-stopped

# To use this Docker Compose file:
# 1. Save it as 'docker-compose.yml' in the root of your repository.
# 2. IMPORTANT: Change the Samba credentials "devuser;devpass" in the command section above.
# 3. Run 'podman-compose up -d' (or 'docker-compose up -d') in the terminal from the repository root.
# 4. Access the Samba share from your network using the host machine's IP address
#    and the share name 'tasks' with the credentials you set.
#    You will likely need to specify the custom port for SMB (e.g., 1445) if your client doesn't automatically try it.
#    Example for Windows Explorer: \\\\<host_ip>\\tasks (Windows might still try 445 by default,
#    you might need to connect via 'Map network drive' and specify the port if direct access fails,
#    or ensure your client supports non-standard SMB ports. For Linux clients, you might use:
#    smbclient //<host_ip>/tasks -U devuser -p 1445 )
#    Note: Accessing Samba on non-standard ports can sometimes be tricky depending on the client OS and software.